In [13]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
DATA_PATH = 'data/seoul_temperature_daily.csv'
temp_data = pd.read_csv(DATA_PATH, index_col=0, parse_dates=True)
temp = temp_data["tavg"].values

In [15]:
def indexing(x, arr):
    n = len(x)
    if n==1:
        arr.append(x[0])
        return
    
    even = []
    odd = []
    for i in range(n):
        if i % 2 == 0:
            even.append(x[i])
        else:
            odd.append(x[i])
    indexing(even, arr)
    indexing(odd, arr)

In [16]:
x = np.arange(0,8)
arr = []
indexing(x,arr)
arr =  np.array(arr)
print(arr)

n = 8
prev_order = [0,1,2,3,-4,-3,-2,-1]
test_ret =   [0,1,2,3,4,5,6,7]
expect_ret = [0,1,7,2,6,3,5,4]

order = [0]
for i in range(1,n//2):
    order.extend([-i,i])
order.append(n//2)

print(order)
reordered_ret = x[[m % n for m in order]]
print(reordered_ret) 

[0 4 2 6 1 5 3 7]
[0, -1, 1, -2, 2, -3, 3, 4]
[0 7 1 6 2 5 3 4]


In [17]:
PI = np.arccos(-1)
print(PI)

3.141592653589793


In [18]:
def fft(x):
    l = len(x)
    N = 1
    n_list = [1]
    while N<l:
        N<<=1
        if N<l:
            n_list.append(N)

    temp_x = np.arange(N)
    arr = []
    indexing(temp_x, arr)
    init_index = np.array(arr)
    
    prev_result = np.zeros(N)
    curr_result = np.zeros(N)
    X = np.zeros(N)
    

    for n in n_list:
        if n == 1 :
            for i in range(N//2):
                even_idx = i*2
                odd_idx = even_idx+1
                even = init_index[even_idx]
                odd = init_index[odd_idx]

                prev_result[even_idx] = even + odd
                prev_result[odd_idx] = even - odd

            prev_result, curr_result = curr_result, prev_result

        else:
            idx = 0
            for i in range((N//2)//n):
                w_ = np.exp(i*2.0*PI/ (n*2))
                
                for j in range(n):
                    w = 1
                    even_idx = idx
                    odd_idx = idx+n
                    even = prev_result[even_idx]
                    t = prev_result[odd_idx] * w
                    curr_result[even_idx]  = even + t
                    curr_result[odd_idx]  = even - t
                    idx+=1
                    w*=w_

                idx+=n
            prev_result, curr_result = curr_result, prev_result
    
    return prev_result

In [19]:
x = np.array([2.0,3.0,0.0,0.0])
x_ret = fft(x)
print(x_ret)

[0. 0. 0. 0.]
